name: Deploy to prod env
on:
    push:
        branches:
            - main
jobs:
    build-docker:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                  token: ${{ secrets.PRIVATE_TOKEN }}
                  submodules: true

            - name: Create SSH key
              run: |
                mkdir -p ~/.ssh/
                echo "$SSH_PRIVATE_KEY" > ../private.key
                sudo chmod 600 ../private.key
                echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
              shell: bash
              env:
                SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}

            - name: Build and deploy
              run: ssh -i $SSH_KEY_PATH $SSH_USER@$SSH_KNOWN_HOSTS '~/build.sh'
              env:
                SSH_USER: ${{secrets.SSH_USER}}
                SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
                SSH_KEY_PATH: ${{ github.workspace }}/../private.key

            - name: slack-notification
              uses: 8398a7/action-slack@v3
              with:
                  status: ${{ job.status }}
                  author_name: Github Action Test # default: 8398a7@action-slack
                  fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
              env:
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
              if: always() # Pick up events even if the job fails or is canceled.
