name: deploy documentation

on: [push]

jobs:
    deploy-docs:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
              with:
                token: ${{ secrets.PRIVATE_TOKEN }}
                submodules: true

            - name: setup jdk 11
              uses: actions/setup-java@v2
              with:
                distribution: 'adopt'
                java-version: '11'
                cache: 'gradle'

            - name: Start Redis
              uses: supercharge/redis-github-action@1.1.0
              with:
                redis-version: 6

            - name: add permission to gradlew
              run: chmod +x ./gradlew
              shell: bash

            - name: generate docs
              run: ./gradlew asciidoctor
              shell: bash

            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v1.2
              with:
                  publish-dir: './build/docs/asciidoc'
                  production-branch: dev
                  github-token: ${{ secrets.PRIVATE_TOKEN }}
                  deploy-message: 'Deploy from GitHub Actions'
                  enable-pull-request-comment: false
                  enable-commit-comment: false
                  overwrites-pull-request-comment: false
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
              timeout-minutes: 1
