name: Ktlint check
on: [pull_request]

jobs:
    ktlint:
        name: Check Code Quality
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@main
              with:
                  fetch-depth: 1

            - name: add permission to gradlew
              run: chmod +x ./gradlew
              shell: bash

            - name: test
              run: ./gradlew ktlintCheck
              shell: bash
