name: Ktlint check
on: [pull_request]

jobs:
    ktlint:
        name: Check Code Quality
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@main
              with:
                  fetch-depth: 1

            - name: setup jdk 11
              uses: actions/setup-java@v2
              with:
                  distribution: 'adopt'
                  java-version: '11'
                  cache: 'gradle'

            - name: add permission to gradlew
              run: chmod +x ./gradlew
              shell: bash

            - name: test
              run: ./gradlew ktlintCheck
              shell: bash
