name: Ktlint check
on: [pull_request]

jobs:
    ktlint:
        name: Check Code Quality
        runs-on: ubuntu-latest

        steps:
            - name: Clone repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 1

            - name: setup jdk 21
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '21'
                  cache: 'gradle'

            - name: add permission to gradlew
              run: chmod +x ./gradlew
              shell: bash

            - name: test
              run: ./gradlew ktlintCheck
              shell: bash
